name: ever_cache
description: Allows to cache a computed value for a specific duration.
version: 0.0.8
repository: https://github.com/ArunPrakashG/ever_cache

environment:
  sdk: ^3.4.3

dependencies:

dev_dependencies:
  test: ^1.24.0
  personal_flutter_lints:
    git:
      url: https://github.com/ArunPrakashG/personal_flutter_lints.git
      ref: main
